name: Merge EPG Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to push changes

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest

    env:
      EPG_URL_1: ${{ secrets.EPG_URL_1 }}
      EPG_URL_2: ${{ secrets.EPG_URL_2 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG merge script
        run: python merge_epg.py

      - name: Set authenticated git remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push merged EPG
        run: |
          git config user.name "EPG Bot"
          git config user.email "epg-bot@example.com"
          git add merged_epg.xml
          git commit -m "Update merged EPG [auto]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
