name: Merge EPG Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # 👈 THIS GIVES PUSH ACCESS TO GITHUB_TOKEN

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-dotenv requests

      - name: Run EPG merge script
        run: python merge_epg.py

      - name: Set authenticated git remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit changes
        run: |
          git config user.name "EPG Bot"
          git config user.email "epg-bot@example.com"
          git add merged_epg.xml
          git commit -m "Update merged EPG [auto]" || echo "No changes to commit"
          git push origin HEAD:main
